version: 2
jobs:
  build:
    macos:
      xcode: 13.3.0
    working_directory: "~/{{PROJECT_NAME}}"
    environment:
      FL_OUTPUT_DIR: ~/fl_output
    shell: /bin/bash --login -o pipefail
    steps:
      # load all SSH keys from the CircleCI project settings
      # in order to be able to pull the ios signing repository
      - add_ssh_keys:
      # setup NPM & ns cli
      - run: mkdir ~/npm_prefix/
      - run: echo 'export PATH=~/npm_prefix/node_modules/.bin:$PATH' >> $BASH_ENV
      - run: node -v && npm -v
      - restore_cache:
          keys:
            - node-modules-macos-{{CLI_VERSION}}
      - run: ns --version || (pushd ~/npm_prefix && npm i nativescript@{{CLI_VERSION}} && popd)
      - save_cache:
          paths:
            - ~/npm_prefix/node_modules/
          key: node-modules-macos-{{CLI_VERSION}}
      
      # Disable usage & error reporting
      - run: ns usage-reporting disable
      - run: ns error-reporting disable

      - checkout

      # NODE PACKAGES
      - run: npm install

      # INSTALL GEMS
      - restore_cache:
          key: gems-macos-{{ checksum "Gemfile" }}
      - run: bundle config set path 'vendor/bundle'
      - run: bundle install
      - save_cache:
          key: gems-macos-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run: pod repo update
      - run:
          name: Fastlane
          command: bundle exec fastlane ios build
      - store_artifacts:
          path: ~/fl_output/{{PROJECT_NAME}}.ipa
          destination: "~/output/{{OUTPUT_APP_FILENAME}}"
      - store_artifacts:
          path: ~/fl_output/{{PROJECT_NAME}}.app.zip
          destination: "~/output/{{OUTPUT_APP_FILENAME}}.zip"

workflows:
  version: 2
  workflow:
    jobs:
      - build
